HTTP:
  ADDRESS: "localhost:8080"

POSTGRES:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: user
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_DB: DelayedNotifier
  MAX_CONNS: 10
  MIN_CONNS: 5
  POSTGRES_DSN: postgres://user:user@localhost:5432/DelayedNotifier

RABBITMQ:
  URL: amqp://guest:guest@localhost:5672/
  CONNECTION_NAME: DelayedNotifier
  EXCHANGE: delayed.notifier